
services:
  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_EDITOR_BASE_URL=http://localhost:8081
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_SECURITY_AUDIT_DAYS=7
      - GENERIC_TIMEZONE=UTC
      - WEBHOOK_URL=http://localhost:8081
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      - N8N_PUSH_BACKEND=websocket
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_ALLOWED_ORIGINS=*
      - N8N_PROXY_HOPS=1
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - n8n_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - n8n
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge
